### ISSUE TITLE
Example docker-compose.yaml failes due to no tag `latest` published on Docker Hub 

### ISSUE THREAD

**Issue by hoh** [aleph-im/p2p-service#35]
Tags on Docker Hub: https://hub.docker.com/r/alephim/p2p-service/tags
Exemple using docker-compose: https://github.com/aleph-im/p2p-service/blob/main/scripts/demo/docker-compose.yml

**Comment by odesenfans** [comment]
[Fixed](https://hub.docker.com/layers/alephim/p2p-service/latest/images/sha256-cc58d029175e4936ac79180ce899a78a1586a93387dab5ee2c1cd873aca21c83?context=explore).
